### ISSUE TITLE
Arm in Hassio

### ISSUE THREAD

**Issue by pengemetal** [maragelis/ParadoxMqtt32#19]
Hi,

I can see in Home assistant every motion sensors, but I can't arm the alarm sysem remotly.  I think the problem is /Arm topic returns 0 (or 1) Home assistant needs "armed", "disarmed" ..etc. Could anyone help with a HA config wich works? Thank you!

**Comment by maragelis** [comment]
its not 0/1 the topic is paradox32CTL/hassio/Arm/0 where 0 is the partition number 
At that topic the values are  "armed", "disarmed"
so change your topic to the above and it should work

**Comment by pengemetal** [comment]
Thx for your answer! It is very interesting, I am listening paradox32CTL1/hassio/Arm/0 and it seems to be an empty message. I use Mqtt explorer and I can see the same. Is it possible Paradox doesn't send the status?
![image](https://user-images.githubusercontent.com/56131015/117052373-f0c18700-ad17-11eb-961a-e5af92453c0e.png)

**Comment by maragelis** [comment]
Click on ARM 
![image](https://user-images.githubusercontent.com/12981331/117117739-90bef500-ad98-11eb-90ba-d1216838083c.png)
![image](https://user-images.githubusercontent.com/12981331/117117860-b5b36800-ad98-11eb-9e18-cf4cf0722da4.png)

**Comment by pengemetal** [comment]
It is empty 
![image](https://user-images.githubusercontent.com/56131015/117121243-a16d6c00-ad94-11eb-94fc-f6d74cc43179.png)

**Comment by maragelis** [comment]
are you able to arm and disarm the system ?
Try doing it manually from the keypad it should update the arm status.

**Comment by pengemetal** [comment]
Oh, thank you very much! It needs a manually arming first! Works fine in HA too! :)
![image](https://user-images.githubusercontent.com/56131015/117123896-e8109580-ad97-11eb-9fa1-4bf7a507bbde.png)

**Comment by maragelis** [comment]
ok good job
