### ISSUE TITLE
How to compile the project on Arduino IDE (no .ino file)

### ISSUE THREAD

**Issue by qntris** [maragelis/ParadoxMqtt32#23]
Hello, perhaps a noob question, but what am I supposed to do in order to successfully compile the project in the Arduino IDE? I have already made sure that ESP32 board libraries are installed, tested my ESP32 board with a simple "BLINK_LED" sketch and it is working fine.
However, I am not able to load the project in Arduino - there's no .ino file in it and whatever I seem to try - fails.

**Comment by tasosstr** [comment]
This code are for use in Platform.io with VScode ( much better editor from arduino ...)

See here https://www.youtube.com/watch?v=dany7ae_0ks  how to use it.

Enjoy.
