### ISSUE TITLE
Home assistant config

### ISSUE THREAD

**Issue by pengemetal** [maragelis/ParadoxMqtt32#8]
Hi, 

Does anyone use HA integration? How could I config. I can see in Mqtt Explorer the following, but I can not see any sensor state or sensor mqtt message, only the arm status (in Homekit topic) :

![image](https://user-images.githubusercontent.com/56131015/106887635-b8dd8000-66e5-11eb-922a-d800b04c09cd.png)

Thx

**Comment by maragelis** [comment]
that’s the default message when the controller starts. As soon as you arm disarm you should start getting messages on the hassio message queue.

**Comment by pengemetal** [comment]
> that’s the default message when the controller starts. As soon as you arm disarm you should start getting messages on the hassio message queue.

I tried, but nothing happened :(
I only get message from motion/door while armed?

**Comment by maragelis** [comment]
What panel are you using ?

**Comment by pengemetal** [comment]
ESP32 devkit1, I can try a devkit3

**Comment by maragelis** [comment]
No what alarm panel are you using ?

**Comment by maragelis** [comment]
Just updated the code with some major updates. just re-flash with the new code and try again.

**Comment by pengemetal** [comment]
SP5000 with remote  GSM security service (but it is not connect to the serial port

**Comment by maragelis** [comment]
Thats my bench panel used to create this project. So you should be ok.

**Comment by pengemetal** [comment]
Thank you for the code! I managed to see the sensor state once! :) After reconnect I didn't. I think my wifi is too far from the paradox. I will try to fix the problem
